### ISSUE TITLE
关于参数调节

### ISSUE THREAD

**Issue by jianjiandandande** [HonglinChu/SiamTrackers#15]
可以分享一下单目标跟踪里面关于参数调节的一些技巧吗

**Comment by HonglinChu** [comment]
关于参数调节，商汤开源的pysot里面，有一个hp_search.py的文件用于自动调参；可调节的参数有：乘法因子，学习滤，窗口影响因子，搜索区域大小等

**Comment by jianjiandandande** [comment]
好，我试试

**Comment by HonglinChu** [comment]
Alexnet version are 20 epochs,&nbsp; &nbsp;resnet50 version are 50 epochs




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月5日(星期一) 下午4:38
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] About train epoch (#15)





 
The number of training times of SiamRPN++ in the original paper is 20 epochs, but you have trained 40 and 50 epochs.

**Comment by jianjiandandande** [comment]
好的，谢谢啦

**Comment by jianjiandandande** [comment]
> Alexnet version are 20 epochs,&nbsp; &nbsp;resnet50 version are 50 epochs
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月5日(星期一) 下午4:38 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] About train epoch (#15) The number of training times of SiamRPN++ in the original paper is 20 epochs, but you have trained 40 and 50 epochs. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

On the contrary, Alexnet version are 50 epochs,&nbsp; &nbsp;resnet50 version are 20 epochs, I looked at the source code carefully

**Comment by HonglinChu** [comment]
I am sorry，my previous explanation&nbsp; was worng.&nbsp; &nbsp;you are right, we only train the siamrpn++ of&nbsp;&nbsp;alexnet version, so the maximum epoch is 50.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "gaowenxing"<notifications@github.com&gt;; 
发送时间: 2020年10月12日(星期一) 晚上9:58
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 关于参数调节 (#15)





  
Alexnet version are 20 epochs,&nbsp; &nbsp;resnet50 version are 50 epochs
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年10月5日(星期一) 下午4:38 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] About train epoch (#15) The number of training times of SiamRPN++ in the original paper is 20 epochs, but you have trained 40 and 50 epochs. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
On the contrary, Alexnet version are 50 epochs,&nbsp; &nbsp;resnet50 version are 20 epochs, I looked at the source code carefully
