### ISSUE TITLE
关于UpdateNet训练连数据集问题

### ISSUE THREAD

**Issue by ShiLongCheng** [HonglinChu/SiamTrackers#24]
您好，我用您提供的程序在ubuntu16.04下面生成训练数据时出现MemoryError问题。当我按照网上的说明 `cat /proc/sys/vm/overcommit_memory`改为`1`时，又显示`已杀死`，没法生成训练数据。请问您是否遇到过同样的问题。或者您是否能够把训练数据分享一下，谢谢。

**Comment by ShiLongCheng** [comment]
您好，这个问题我又解决了，是内存不够的问题，还是得`加硬件`才行。借了实验室小伙伴的内存条凑成了32g内存。据我实际操作，按照您提供的那20个视频数据生成训练数据时，大概要用`23g`左右的运行内存。

**Comment by HonglinChu** [comment]
我没遇到过这个问题，你用vscode单步调试一下，找找是那一步代码错了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月12日(星期六) 晚上11:50
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24)





 
您好，我用您提供的程序在ubuntu16.04下面生成训练数据时出现MemoryError问题。当我按照网上的说明 cat /proc/sys/vm/overcommit_memory改为1时，又显示已杀死，没法生成训练数据。请问您是否遇到过同样的问题。或者您是否能够把训练数据分享一下，谢谢。

**Comment by HonglinChu** [comment]
解决了就好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alfredcheng"<notifications@github.com&gt;; 
发送时间: 2020年12月13日(星期天) 下午3:37
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24)





 
您好，这个问题我又解决了，是内存不够的问题，还是得加硬件才行。借了实验室小伙伴的内存条凑成了32g内存。据我实际操作，按照您提供的那20个视频数据生成训练数据时，大概要用23g左右的运行内存。

**Comment by ShiLongCheng** [comment]
> 我没遇到过这个问题，你用vscode单步调试一下，找找是那一步代码错了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月12日(星期六) 晚上11:50 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24) 您好，我用您提供的程序在ubuntu16.04下面生成训练数据时出现MemoryError问题。当我按照网上的说明 cat /proc/sys/vm/overcommit_memory改为1时，又显示已杀死，没法生成训练数据。请问您是否遇到过同样的问题。或者您是否能够把训练数据分享一下，谢谢。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，这个问题我已经解决了。但是我生成训练数据后，训练时始终没有达到0.403，最多0.363好像。不知道为什么。是我哪里没考虑到吗？还有您哪个README里面讲的我没有看太懂。每个阶段怎么训练的？

**Comment by ShiLongCheng** [comment]
还有一点，我是觉得updatenet只用了两层1x1的效果就挺好的了，感觉不太合理啊。毕竟两层线性的网络，而且是1x1的网络融合能力有点差吧，原作者为什么不加深一下？

**Comment by HonglinChu** [comment]
我没尝试过加深，应该是两层就够了，两层1x1，只用了一个relu，个人感觉非线性表达不够。Updatenet主要是进行通道交互，1x1卷积进行通道降维和升维来实现。关于updatenet可以微信上交流






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alfredcheng"<notifications@github.com&gt;; 
发送时间: 2020年12月14日(星期一) 下午3:10
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24)





 
还有一点，我是觉得updatenet只用了两层1x1的效果就挺好的了，感觉不太合理啊。毕竟两层线性的网络，而且是1x1的网络融合能力有点差吧，原作者为什么不加深一下？

**Comment by ShiLongCheng** [comment]
> 我没尝试过加深，应该是两层就够了，两层1x1，只用了一个relu，个人感觉非线性表达不够。Updatenet主要是进行通道交互，1x1卷积进行通道降维和升维来实现。关于updatenet可以微信上交流
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alfredcheng"<notifications@github.com&gt;; 发送时间: 2020年12月14日(星期一) 下午3:10 收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24) 还有一点，我是觉得updatenet只用了两层1x1的效果就挺好的了，感觉不太合理啊。毕竟两层线性的网络，而且是1x1的网络融合能力有点差吧，原作者为什么不加深一下？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，您的微信号是多少啊，我没找到。^-^

**Comment by HonglinChu** [comment]
18374967041




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alfredcheng"<notifications@github.com&gt;; 
发送时间: 2020年12月15日(星期二) 上午10:55
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24)





  
我没尝试过加深，应该是两层就够了，两层1x1，只用了一个relu，个人感觉非线性表达不够。Updatenet主要是进行通道交互，1x1卷积进行通道降维和升维来实现。关于updatenet可以微信上交流
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alfredcheng"<notifications@github.com&gt;; 发送时间: 2020年12月14日(星期一) 下午3:10 收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HonglinChu/SiamTrackers] 关于UpdateNet训练连数据集问题 (#24) 还有一点，我是觉得updatenet只用了两层1x1的效果就挺好的了，感觉不太合理啊。毕竟两层线性的网络，而且是1x1的网络融合能力有点差吧，原作者为什么不加深一下？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，您的微信号是多少啊，我没找到。^-^
