### ISSUE TITLE
UpdateNet训练效果问题。

### ISSUE THREAD

**Issue by ShiLongCheng** [HonglinChu/SiamTrackers#27]
您好，我又来问问题了，不好意思问题有点多。我按照您的README文件训练后发现越训练越差，不知道怎么回事。我在训练过程中，每个stage x-1学习率设置为`lrs = np.array([[6,7],[7,8]])`，每个stage x-2学习率设置为`lrs = np.array([[8,9],[9,10]])`。在进行下一阶段训练前都会加载上一阶段的最好模型生成新的训练数据，但是效果是越来越差，不知道怎么回事，感觉很迷惑。

**Comment by HonglinChu** [comment]
如果效果不好学习率设置的密集一些，最好把学习率多设置几个， 例如 [[5,5],[5,6],[6,6],[6,7],[7,7],[7,8],[8,8],[8,9],[9,9],[9,10]，[10,10],[10,11],[11,11]];&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "HonglinChu/SiamTrackers"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月22日(星期二) 上午10:08
收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27)





 
您好，我又来问问题了，不好意思问题有点多。我按照您的README文件训练后发现越训练越差，不知道怎么回事。我在训练过程中，每个stage x-1学习率设置为lrs = np.array([[6,7],[7,8]])，每个stage x-2学习率设置为lrs = np.array([[8,9],[9,10]])。在进行下一阶段训练前都会加载上一阶段的最好模型生成新的训练数据，但是效果是越来越差，不知道怎么回事，感觉很迷惑。

**Comment by ShiLongCheng** [comment]
> 如果效果不好学习率设置的密集一些，最好把学习率多设置几个， 例如 [[5,5],[5,6],[6,6],[6,7],[7,7],[7,8],[8,8],[8,9],[9,9],[9,10]，[10,10],[10,11],[11,11]];&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:08 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27) 您好，我又来问问题了，不好意思问题有点多。我按照您的README文件训练后发现越训练越差，不知道怎么回事。我在训练过程中，每个stage x-1学习率设置为lrs = np.array([[6,7],[7,8]])，每个stage x-2学习率设置为lrs = np.array([[8,9],[9,10]])。在进行下一阶段训练前都会加载上一阶段的最好模型生成新的训练数据，但是效果是越来越差，不知道怎么回事，感觉很迷惑。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

您好，感谢您的回答，感觉updatenet模型非常不好训练-_-。假如我设置了三组学习率lr5-6,lr6-7,lr7-8，每组学习率单独学习50个epoch，也就是总共保存了3x50个模型，然后在VOT2018中测试，从3x50个模型中找出这三组学习率中效果最好的那个checkpointxx作为下一阶段的模型，是我这样理解的吗？要是设置了10组，那么则保存了10x50个模型？

**Comment by HonglinChu** [comment]
是的



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "alfredcheng"<notifications@github.com&gt;; 
发送时间: 2020年12月22日(星期二) 下午3:11
收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 
抄送: "SmallLion🦁️"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27)





  
如果效果不好学习率设置的密集一些，最好把学习率多设置几个， 例如 [[5,5],[5,6],[6,6],[6,7],[7,7],[7,8],[8,8],[8,9],[9,9],[9,10]，[10,10],[10,11],[11,11]];&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:08 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27) 您好，我又来问问题了，不好意思问题有点多。我按照您的README文件训练后发现越训练越差，不知道怎么回事。我在训练过程中，每个stage x-1学习率设置为lrs = np.array([[6,7],[7,8]])，每个stage x-2学习率设置为lrs = np.array([[8,9],[9,10]])。在进行下一阶段训练前都会加载上一阶段的最好模型生成新的训练数据，但是效果是越来越差，不知道怎么回事，感觉很迷惑。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
您好，感谢您的回答，感觉updatenet模型非常不好训练-_-。假如我设置了三组学习率lr5-6,lr6-7,lr7-8，每组学习率单独学习50个epoch，也就是总共保存了3x50个模型，然后在VOT2018中测试，从3x50个模型中找出这三组学习率中效果最好的那个checkpointxx作为下一阶段的模型，是我这样理解的吗？要是设置了10组，那么则保存了10x50个模型？

**Comment by ShiLongCheng** [comment]
> 是的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "alfredcheng"<notifications@github.com&gt;; 发送时间: 2020年12月22日(星期二) 下午3:11 收件人: "HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送: "SmallLionlion"<1628464345@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 主题: Re: [HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27) 如果效果不好学习率设置的密集一些，最好把学习率多设置几个， 例如 [[5,5],[5,6],[6,6],[6,7],[7,7],[7,8],[8,8],[8,9],[9,9],[9,10]，[10,10],[10,11],[11,11]];&nbsp; … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "HonglinChu/SiamTrackers" <notifications@github.com&gt;; 发送时间:&nbsp;2020年12月22日(星期二) 上午10:08 收件人:&nbsp;"HonglinChu/SiamTrackers"<SiamTrackers@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;[HonglinChu/SiamTrackers] UpdateNet训练效果问题。 (#27) 您好，我又来问问题了，不好意思问题有点多。我按照您的README文件训练后发现越训练越差，不知道怎么回事。我在训练过程中，每个stage x-1学习率设置为lrs = np.array([[6,7],[7,8]])，每个stage x-2学习率设置为lrs = np.array([[8,9],[9,10]])。在进行下一阶段训练前都会加载上一阶段的最好模型生成新的训练数据，但是效果是越来越差，不知道怎么回事，感觉很迷惑。 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. 您好，感谢您的回答，感觉updatenet模型非常不好训练-_-。假如我设置了三组学习率lr5-6,lr6-7,lr7-8，每组学习率单独学习50个epoch，也就是总共保存了3x50个模型，然后在VOT2018中测试，从3x50个模型中找出这三组学习率中效果最好的那个checkpointxx作为下一阶段的模型，是我这样理解的吗？要是设置了10组，那么则保存了10x50个模型？ — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

感谢，感谢。我再试一试，然后再改改iou
